### PR TITLE
auto-dismiss notifications

### PR DESCRIPTION
**Pull request by agilbert**

### CODE REVIEW

**Comment by agilbert** [comment]
See https://github.com/punkave/apostrophe/issues/928

**Comment by boutell** [comment]
This currently uses dismiss: true for both errors and "mere" notifications. I think that you should use it in a more nuanced way.

**Comment by stuartromanek** [comment]
Don't dismiss error messages

**Comment by bobclewell** [comment]
@boutell or @stuartromanek can we close this based on the above comments?

**Comment by boutell** [comment]
It still needs to actually be adjusted to not pass the dismiss option when the type is error.

**Pull request closed without merging**
